spring:
  datasource:
    #url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:C:/Users/manoj/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example.demo: DEBUG